Repository CSC207-2022F-UofT/course-project-budgetbites, pull requests merged in 2022-12, with the labels that each got.

#101 Created temp userSuggestionFrame, to be utilized for userSuggestions
  src/main/java/main.java
  src/main/java/ui/userSuggestionFrame.java
Labels: enhancement

#105 The Login Frame now linked with Login and Mongo DB
  src/main/java/entities/PastOrders.java
  src/main/java/ui/LoginFrame.java
  src/main/java/usecases/login/CurrentUser.java
  src/main/java/usecases/login/NewUser.java
Labels: enhancement

#114 Created an Interface to be able to access MainMongoDB in Budget manager and refactored methods and tests of budget manager accordingly
  src/main/java/Frames/UserChangeBudgetFrame.java
  src/main/java/gateways/MainMongoDB.java
  src/main/java/usecases/BudgetDAI.java
  src/main/java/usecases/budgeting/BudgetManager.java
  src/test/java/BudgetManagerTest.java
Labels: enhancement

#132 LogicCodeTest and LoginTest
  src/main/java/ui/SignUpFrame.java
  src/main/java/usecases/login/LogicCode.java
  src/main/java/usecases/login/Login.java
  src/test/java/usecases/login/LogicCodeTest.java
  src/test/java/usecases/login/LoginTest.java
Labels: testing

#143 Fixed the functionality of the order button in ItemFrameCart
  src/main/java/ui/ItemCartFrame.java
  src/main/java/usecases/BudgetDAI.java
  src/main/java/usecases/budgeting/BudgetManager.java
  src/test/java/BudgetManagerTest.java
Labels: bug
